services:
    KimaiPlugin\FastEntryBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,Resources,vendor}'

    KimaiPlugin\FastEntryBundle\Controller\FastEntryController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $timesheetRepository: '@App\Repository\TimesheetRepository'