services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\FastEntryBundle\:
        resource: '../../'
        exclude:
            - '../../Migrations/'
            - '../../Resources/'
            - '../../vendor/'
            - '../../.github/'

    KimaiPlugin\FastEntryBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']